#!/usr/bin/env ruby

$stdout.sync = true

require "bundler/setup"
require "superscript"
require "optparse"

options = {
  methods: false,
  on_error_exec: nil
}
ARGV << "-h" if ARGV.empty?

optparse = OptionParser.new do |opt|
  opt.on('--allow-methods') { |o| options[:methods] = true }
  opt.on('--on-error-exec CMD') { |o| options[:on_error_exec] = o }
end.parse!

best_guess_path = if ARGV[0].start_with? "/"
  ARGV[0]
else
  File.join(".", ARGV[0])
end

require best_guess_path

ctx_classname = File.basename(ARGV[0]).split(".").first.capitalize
ctx = (eval "#{ctx_classname}").new

if ARGV[1]
  runner = Superscript::Runner.new ARGV[1], options
  runner.run! ctx
else
  runner = Superscript::Runner.new nil, options
  loop do
    print "> "
    contents = STDIN.gets
    value = runner.run! ctx, contents: contents
    puts " => #{value.inspect}"
  end
end
